homepage/urls.py
from django.urls import include, path
from . import views
from django.contrib import admin

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirmation/', views.confirmation, name='confirmation')
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

#Create your models here.
class Status(models.Model): 
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=255)

    def __str__(self):
        return self.name

homepage/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name', 'status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Status
from .forms import StatusForm

# Create your views here.
def index(request):
    status = Status.objects.all()
    if (request.method == 'POST'):
        form = StatusForm(request.POST)
        if (form.is_valid()):
            new = Status()
            new.name = form.cleaned_data['name']
            new.status = form.cleaned_data['status']    
            response = {'name':new.name, 'status':new.status}
            return render(request, 'confirmation.html', response)
    else:
        form = StatusForm()
            
    response = {'status':status, 'form':form}
    return render(request, 'index.html', response)

def confirmation(request):
    if (request.method == 'POST'):
        form = StatusForm(request.POST)
        if (form.is_valid()):
            new = Status()
            new.name = form.cleaned_data['name']
            new.status = form.cleaned_data['status']
            new.save()
            return redirect('/')
    else:
        form = StatusForm()

    response = {'form':form}
    return render(request, 'confirmation.html', response)

homepage/templates/confirmation.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <title>Status Confirmation</title>

  </head>

  <body>
      <br>
      <h class="font-weight-bold" style="font-size: 5vh; margin-left: 8.7%;">Confirmation</h>
      <form action="{% url 'homepage:confirmation' %}" method="post">
        {% csrf_token %}
        <div style="margin-left: 10px; margin-right: 10px;">
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                <div class="form-group">
                    <label for="name" class="form-label">Name: {{ name }}</label>
                    <input class="form-control" id="name" type="hidden" name="name" value="{{ name }}" readonly>
                </div>

                <div class="form-group">
                    <label for="status" class="from-label">Status: {{ status }}</label>
                    <input class="form-control" id="status" type="hidden" name="status" value="{{ status }}" readonly>
                </div>
            </div>
        </div>
        <div class="row">
            <input name="save" id="submitBtn" type="submit" class="btn btn-secondary" style="margin-left: 8.7%;" value="Save">
            <a class="btn btn-secondary" href="{% url 'homepage:index' %}" role="button" name="back" style="margin-left: 1%;">Back</a>
        </div>
      </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

homepage/templates/index.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <title>Story 7</title>

  </head>

  <body>
      <br>
      <h class="font-weight-bold" style="font-size: 5vh; margin-left: 8.7%;">Hello, how are you?</h>
      <form method="post" action="{% url 'homepage:index' %}">
        {% csrf_token %}
        <div style="margin-left: 10px; margin-right: 10px;">
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                {% for fields in form %}
                    {{ fields.label_tag }}
                    <br>
                    {{ fields }}
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <input name="submit" id="submitBtn" type="submit" class="btn btn-secondary" style="margin-left: 8.7%;" value="Submit">
        </div>
      </form>

      <br><br>
      <div class="container-fluid">
        <div class="row text-center">
          <div class="col">
            <h class="font-weight-bold" style="font-size: 5vh;">Status List</h>
          </div>
        </div>
      </div>
      <br>
      <table id="statustable" class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          {% for i in status %}
            <tr class="table-info">
              <td class="table-secondary">{{ i.name }}</td>
              <td class="table-info">{{ i.status }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>